server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://luowen:666@localhost:8761/eureka
  #eureka控制台的System Status信息
  environment: prd
  datacenter: cloud
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: microservice-gateway-zuul
zuul:
  #禁用代理所有服务
  ignored-services:  '*'
  #只代理所配置的服务，并启用别名
  routes:
    microservice-provider-user: /user/**
