server:
  port: 8083

#获取git上的资源信息遵循如下规则
#/{application}/{profile}[/{label}]
#/{application}-{profile}.yml
#/{label}/{application}-{profile}.yml
#/{application}-{profile}.properties
#/{label}/{application}-{profile}.properties
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VirgilLone/spring-cloud-config-repository
