server:
  port: 8010

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000


eureka:
  client:
    service-url:
      defaultZone: http://luowen:666@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: microservice-consumer-mover-ribbon-with-hystrix