server:
  port: 8031

eureka:
  client:
    service-url:
      defaultZone: http://luowen:666@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: microservice-hystrix-turbine

turbine:
  aggregator:
    clusterConfig: default
  #spring.application.name 配置要监控的集群，可逗号隔开
  app-config: microservice-consumer-mover-ribbon-with-hystrix,microservice-consumer-movie-feign-with-hystrix
  cluster-name-expression: new String("default")
